### ISSUE TITLE
Unable to import audio file

### ISSUE THREAD

**Issue by Tannister** [AntonioDePau/GHDS_ModdingTool#21] opened 2023-07-14 21:28 UTC
![image](https://github.com/AntonioDePau/GHDS_ModdingTool/assets/36128673/ad4ea62e-da5a-41c7-b8d7-c0dd122be0b7)

this happens when putting mono audio files (same thing with wav and ogg)

**Comment by Tannister** [comment] 2023-07-14 21:29
same happen with stereo files

**Comment by AntonioDePau** [comment] 2023-07-15 05:12
> same happen with stereo files

What do you mean? Aren't we able to import stereo files just fine usually?
The error message is about needing to have at least two channels (which I can try and have accept mono), so what does it say when feeding it stereo files?

**Comment by Tannister** [comment] 2023-07-15 07:30
![image](https://github.com/AntonioDePau/GHDS_ModdingTool/assets/36128673/3885c351-ceff-481c-ab66-62d6ba734f39)
Same error message with a stereo file 
(both with ogg and wav)

**Comment by AntonioDePau** [comment] 2023-07-15 08:06
Can you send the stereo file you're getting the error with, please?
(can send on Discord in case there might be copyright infringements)

**Comment by Tannister** [comment] 2023-07-15 08:10
[song.zip](https://github.com/AntonioDePau/GHDS_ModdingTool/files/12060907/song.zip)
Should be good, unmodified audio from ExileLord's Soulless 1

**Comment by AntonioDePau** [comment] 2023-07-15 08:15
It works for me!
Are you sure that's the audio file you're using? In the CallMeWhenYoureSober folder?

Attached is the successfully created hwas:
[Main_song.zip](https://github.com/AntonioDePau/GHDS_ModdingTool/files/12060922/Main_song.zip)

**Comment by AntonioDePau** [comment] 2023-07-15 08:18
Are there any other audio files in the folder? Vocals (those would be merged with song)? Crowd?

**Comment by AntonioDePau** [comment] 2023-07-15 08:19
Pretty sure your problem is caused by your vocals file:
![image](https://github.com/AntonioDePau/GHDS_ModdingTool/assets/23122727/228bd942-9bc3-466a-894d-94471a112e74)

**Comment by Tannister** [comment] 2023-07-15 08:24
I don't have any vocal file in the directory.

**Comment by Tannister** [comment] 2023-07-15 08:27
the song.ogg is the only audio file present.
![image](https://github.com/AntonioDePau/GHDS_ModdingTool/assets/36128673/79769542-7d92-4383-a65c-ce02ce13ae66)
In this image, audio file is from Too Much, Too Young, Too Fast (GHWT), same error.

ModdingTool recompiled today from the main branch

**Comment by AntonioDePau** [comment] 2023-07-15 08:41
I just recompiled from main, and used song.ogg from Too Much, Too Young, Too Fast, and it's working just fine:
![image](https://github.com/AntonioDePau/GHDS_ModdingTool/assets/23122727/5c0f4419-ec7d-4450-a45f-46551b07a008)

Can you possibly try on Windows 10?

**Comment by Tannister** [comment] 2023-07-15 08:42
sadly, no. i don't have any win10 installations here.

**Comment by Tannister** [comment] 2023-07-15 08:49
same thing happens when i try to import guitar & rhythm audio file. :/

**Comment by AntonioDePau** [comment] 2023-07-15 08:54
But you have no issue when using the last release?

There's been no change in main that affects the conversion of OGG or WAV files since, so I can only assume that it's a problem somehow caused at compilation time on Windows 11, since I have no issues after compiling the tool myself on Windows 10, with the same source code you're using...



> same thing happens when i try to import guitar & rhythm audio file. :/

100% exact same error message? The guitar & rhythm audio files should be OGG to begin with and should be decoded and recoded to the correct format, but that's not handled by NAudio.Wave, so that error message should not apply.

**Comment by AntonioDePau** [comment] 2023-07-15 08:55
Could you check the temp audio file (oggtool_audio.temp) in the GHDS_ModdingTool_resources folder, and send it over, please?

**Comment by Tannister** [comment] 2023-07-15 08:56
100% Identical error message with latest exe found in releases.

100% Identical message for all audio files (song, drums, rhythm and guitar)

**Comment by Tannister** [comment] 2023-07-15 08:56
[oggtool_audio.zip](https://github.com/AntonioDePau/GHDS_ModdingTool/files/12061014/oggtool_audio.zip)

That one is with one of the audio files found in embedded_resources from this repo

**Comment by Tannister** [comment] 2023-07-15 08:59
[oggtool_audio.zip](https://github.com/AntonioDePau/GHDS_ModdingTool/files/12061018/oggtool_audio.zip)
This one with Soulless 1 Song.ogg Audio

**Comment by AntonioDePau** [comment] 2023-07-15 09:00
> [oggtool_audio.zip](https://github.com/AntonioDePau/GHDS_ModdingTool/files/12061018/oggtool_audio.zip) This one with Soulless 1 Song.ogg Audio

It's properly converted to a stereo WAV file (if you rename it to .WAV or open it with an hex editor), not sure what the issue is here...

**Comment by AntonioDePau** [comment] 2023-07-15 09:04
> 100% Identical message for all audio files (song, drums, rhythm and guitar)

Can you please try the following:
1. rename your custom_songs folder (to something like custom_songs_backup)
2. drag & drop your BHDS game onto GHDS_ModdingTool.exe
3. put **guitar.ogg** from Soulless 1 into the first folder of the newly created custom_songs folder (All You Need, in the US version, not sure what it is in EU)
4. drag & drop your BHDS game onto GHDS_ModdingTool.exe
5. take a screenshot of the error (if any) and upload it here

**Comment by Tannister** [comment] 2023-07-15 09:08
![image](https://github.com/AntonioDePau/GHDS_ModdingTool/assets/36128673/ffae256e-ea97-4a83-8d29-72857797d4df)

**Comment by AntonioDePau** [comment] 2023-07-15 09:13
Mhhh...

Can you uncomment these lines:
https://github.com/AntonioDePau/GHDS_ModdingTool/blob/main/gh/audio/encoding.cs#L92-L94

And copy paste them at line:
https://github.com/AntonioDePau/GHDS_ModdingTool/blob/main/gh/audio/encoding.cs#L76

Rebuild, try again, and share the screenshot (or copy paste the output of the 3 uncommented/copied lines).

So, it does happen at NAudio.Wave level because of the volume increase during OGG => OGG conversion (where oggdec converts to WAV first, then volume increase happens, and then it should be converted back to OGG, but you're crashing before that).

With the uncommented Console.WriteLine lines, we should be able to know what WAV format the tool is getting.

**Comment by Tannister** [comment] 2023-07-15 09:16
![image](https://github.com/AntonioDePau/GHDS_ModdingTool/assets/36128673/ec277ec7-addf-4de3-8961-8c4a283db3b8)

All 0 ? does not seem correct

**Comment by Tannister** [comment] 2023-07-15 09:18
Added 2 lines to see where we are in the code, we don't hit Encode()
![image](https://github.com/AntonioDePau/GHDS_ModdingTool/assets/36128673/2c7dd579-68f8-4291-b4a5-50af3f1024f3)

**Comment by Tannister** [comment] 2023-07-15 09:22
![image](https://github.com/AntonioDePau/GHDS_ModdingTool/assets/36128673/05121b39-50c8-4a3b-8e53-663ba3a5ca59)

**Comment by Tannister** [comment] 2023-07-15 09:39
![image](https://github.com/AntonioDePau/GHDS_ModdingTool/assets/36128673/43e05662-3192-426f-abb5-116a869a2d5f)

Length of WAV byte array is 0
?

**Comment by AntonioDePau** [comment] 2023-07-15 09:41
> Added 2 lines to see where we are in the code, we don't hit Encode() ![image](https://user-images.githubusercontent.com/36128673/253731670-2c7dd579-68f8-4291-b4a5-50af3f1024f3.png)

Yeah, OGG to OGG doesn't use Encode, just IncreaseVolume.
0 for channels (and the other 2 values) explains why you're getting the error.
As to why you're getting 0...

Try to print the oggFile byte array length here:
https://github.com/AntonioDePau/GHDS_ModdingTool/blob/main/gh/audio/OGG/OGG.cs#L79

**Comment by AntonioDePau** [comment] 2023-07-15 09:42
Oh, and print the output's length as well:
https://github.com/AntonioDePau/GHDS_ModdingTool/blob/main/gh/audio/OGG/OGG.cs#L82

**Comment by Tannister** [comment] 2023-07-15 09:43
![image](https://github.com/AntonioDePau/GHDS_ModdingTool/assets/36128673/dfb5af18-5702-4b57-b25b-9b962862f584)
That one seems valid

**Comment by Tannister** [comment] 2023-07-15 09:45
![image](https://github.com/AntonioDePau/GHDS_ModdingTool/assets/36128673/e9a78325-e882-4ca6-a870-3ca44c881933)
Not the output one.

**Comment by Tannister** [comment] 2023-07-15 09:49
*side note, i put back the old Command Prompt as the default cmd, as it is still available on win11 through developper settings

**Comment by Tannister** [comment] 2023-07-15 09:50
reading the code, shouldnt you read the output file instead of getting the results from StartProcess ?

**Comment by AntonioDePau** [comment] 2023-07-15 09:51
Damned... This will be so much easier if/when Evan manages to give us a fully C# solution for decoding and encoding OGGs.

Okay, we may need to have oggdec write the output to a file and read that file rather than expecting oggdec to feed us back a byte array...

Can you try to update the Ogg.Decode method like so:
```
        public static byte[] Decode(byte[] oggFile){
            string tempFile = Path.Combine(ToolsPath, "oggtool_audio.temp");
            File.WriteAllBytes(tempFile, oggFile);
            
            string Arguments = $" --quiet --output - \"{tempFile}\"";
            byte[] output = StartProcess(Path.Combine(ToolsPath, "oggdec.exe"), Arguments);
            
            return output;
        }
```

Edit: 
This is to try and see if it works by escaping the temp file's path (\"{tempFile}\"), as I suspect you may have whitespaces in your path to the tool

**Comment by AntonioDePau** [comment] 2023-07-15 09:51
> reading the code, shouldnt you read the output file instead of getting the results from StartProcess ?

We'll try, but I really hate having to rely on temp files and write/read them when we SHOULD just be able to feed bytes and get bytes in return.

**Comment by Tannister** [comment] 2023-07-15 09:54
![image](https://github.com/AntonioDePau/GHDS_ModdingTool/assets/36128673/8e0d2887-81b9-4a27-8521-8976e55ca6ca)
Works !

**Comment by AntonioDePau** [comment] 2023-07-15 09:55
Spaces then :D ahahah, glad it was an easy fix. I'll make a commit.

**Comment by Tannister** [comment] 2023-07-15 09:55
huh
![image](https://github.com/AntonioDePau/GHDS_ModdingTool/assets/36128673/fe49ae08-26fb-4a17-9e95-afcf55c12812)
The final file is 0 bytes ..

**Comment by AntonioDePau** [comment] 2023-07-15 09:57
Yeah, the oggenc also needs escaping :p:
```
        public static byte[] Encode(byte[] wavFile, int SampleRate, int BitRate = 18){
            string tempFile = Path.Combine(ToolsPath, "oggtool_audio.temp");
            File.WriteAllBytes(tempFile, wavFile);
            
            string Arguments = $" --quiet --bitrate {BitRate} --resample {SampleRate} --downmix --min-bitrate {BitRate} --max-bitrate {BitRate} -o - \"{tempFile}\"";

            byte[] output = StartProcess(Path.Combine(ToolsPath, "oggenc.exe"), Arguments);
            
            return output;
        }
```

**Comment by Tannister** [comment] 2023-07-15 09:58
there might be other places where escaping is required, glad it was only this

**Comment by AntonioDePau** [comment] 2023-07-15 10:06
We should be fine. The rest of the paths is handled by Path.Combine and other safer methods.
This here was an issue because we're relying on an external tool (oggenc/oggdec) that take path as arguments and I forgot to escape those. But again, hopefully we can have a fully managed C# solution, if Evan can pull it off!

**Comment by Tannister** [comment] 2023-07-15 10:08
Now the presence of Guitar_guitar.ogg causes the issue

(at least that one i can go around easily)

**Closed as completed** 2024-05-08 16:05 UTC
Labels: bug
